package ai.starlake.quack.docs

import ai.starlake.quack.ondemand.api.{ConfigEntry, ConfigRegistry}
import com.typesafe.config.{Config, ConfigFactory}

import java.nio.file.{Files, Paths}
import scala.util.Try

/** Generates the Configuration reference page from `ConfigRegistry` (the same source the admin UI
  * Config page uses) joined with the live default values from `application.conf`. Pure: no server,
  * no DB. Args: [outPath].
  */
object GenConfigDocs:

  /** The six config roots, copied verbatim from Main.scala. */
  def entries: List[ConfigEntry] =
    ConfigRegistry.collect(
      ConfigRegistry.rootsFor(
        managerCls = classOf[ai.starlake.quack.ManagerConfig],
        flightCls = classOf[ai.starlake.quack.FlightConfig],
        authCls = classOf[ai.starlake.quack.edge.config.AuthenticationConfig],
        aclCls = classOf[ai.starlake.quack.edge.config.AclConfig],
        validationCls = classOf[ai.starlake.quack.edge.config.ValidationConfig],
        metricsCls = classOf[ai.starlake.quack.observability.metrics.MetricsConfig]
      )
    )

  private def defaultOf(cfg: Config, path: String): String =
    Try(cfg.getString(path))
      .recover { case _ => Try(cfg.getValue(path).render()).getOrElse("") }
      .getOrElse("")

  private def section(path: String): String =
    val parts = path.split('.')
    if parts.length <= 2 then parts(0)
    else parts.take(2).mkString(".")

  private def escape(s: String): String =
    s.replace("|", "\\|").replace("\n", " ")

  /** Like [[escape]] but also neutralizes MDX-significant characters for prose cells that are NOT
    * wrapped in a code span. Docusaurus parses Markdown as MDX, so a bare `{tenant}` or `<x>` in a
    * description would be read as a JSX expression/element and break the build.
    */
  private def escapeText(s: String): String =
    escape(s).replace("{", "&#123;").replace("}", "&#125;").replace("<", "&lt;")

  def render: String =
    val cfg = ConfigFactory.load()
    val sb  = new StringBuilder
    sb.append("---\n")
    sb.append("id: configuration\n")
    sb.append("title: Configuration reference\n")
    sb.append("sidebar_label: Configuration\n")
    sb.append("---\n\n")
    sb.append(
      "<!-- GENERATED by `sbt genConfigDocs` from ConfigRegistry + application.conf. Do not edit by hand. -->\n\n"
    )
    sb.append("Every scalar accepts the listed `QOD_*` / `PROXY_*` environment-variable override. ")
    sb.append(
      "Sensitive defaults (passwords, secrets, keys) are flagged; rotate them before any non-local deployment.\n\n"
    )

    entries
      .groupBy(e => section(e.path))
      .toList
      .sortBy(_._1)
      .foreach { case (sec, rows) =>
        sb.append(s"## `$sec`\n\n")
        sb.append("| Key | Env var | Default | Sensitive | Description |\n")
        sb.append("| --- | --- | --- | --- | --- |\n")
        rows.foreach { e =>
          val default   = defaultOf(cfg, e.path)
          val defaultMd =
            if e.sensitive then "`***`"
            else if default.isEmpty then "_(unset)_"
            else s"`${escape(default)}`"
          val sensitive = if e.sensitive then "yes" else ""
          sb.append(
            s"| `${e.path}` | `${e.envVar}` | $defaultMd | $sensitive | ${escapeText(e.description)} |\n"
          )
        }
        sb.append("\n")
      }
    sb.toString

  def main(args: Array[String]): Unit =
    val out  = args.headOption.getOrElse("website/docs/reference/configuration.md")
    val md   = render
    val path = Paths.get(out)
    Option(path.getParent).foreach(Files.createDirectories(_))
    Files.writeString(path, md)
    println(s"GenConfigDocs: wrote ${entries.size} config keys to $out")
